version: "3"
services:
  db:
    image: mongo:15.0.14
    ports:
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo:/var/lib/mongodb/data
volumes:
  mongo: ~
